import { test, expect, type Page } from '@playwright/test'

async function verifyLayout(page: Page, name: string, width: number) {
  await expect(page).toHaveTitle('PayLess')
  await expect(page.locator('body')).not.toContainText(/route[ -]?wise|routwise/i)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), name).toBe(true)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `test-results/payless-${name}-${width}-viewport.png`, scale: 'css' })
  await page.screenshot({ path: `test-results/payless-${name}-${width}.png`, fullPage: true })
}

test('branding, navigation, wallet and search layouts at the required viewport widths', async ({ page, request }, testInfo) => {
  test.setTimeout(120_000)
  await request.post('http://127.0.0.1:18000/__control', { data: { mode: 'normal' } })
  const widths = testInfo.project.name === 'desktop' ? [768, 1024, 1440] : [375, 430]
  for (const width of widths) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await expect(page.getByRole('heading', { name: 'How PayLess works' })).toBeVisible()
    await page.getByRole('button', { name: 'Swiggy ₹1,000' }).click()
    await expect(page.getByLabel('What are you paying for?')).toHaveValue("I'm ordering ₹1000 of food on Swiggy")
    await page.getByRole('button', { name: 'Swiggy ₹500', exact: true }).click()
    await verifyLayout(page, 'home', width)
    await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
    await expect(page.getByTestId('best-pay-now')).toHaveText('₹487.50')
    await page.getByRole('button', { name: 'Compare routes' }).click()
    await verifyLayout(page, 'merchant-results', width)
    await page.getByRole('link', { name: 'My Wallet' }).click()
    await verifyLayout(page, 'wallet', width)
    await page.getByRole('button', { name: 'Add payment method', exact: true }).click()
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(dialog).not.toBeVisible()
    await expect(page.getByRole('button', { name: 'Add payment method', exact: true })).toBeFocused()
    await page.getByRole('link', { name: 'Travel', exact: true }).click()
    await verifyLayout(page, 'travel-form', width)
    await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
    await expect(page.getByTestId('best-pay-now')).toHaveText('₹5,459')
    await verifyLayout(page, 'travel-results', width)
    await page.getByRole('link', { name: 'PayLess home' }).click()
    await expect(page.getByLabel('What are you paying for?')).toBeVisible()
  }
})

test('wallet empty state, safe add fields, persistence and keyboard navigation', async ({ page }) => {
  await page.goto('/wallet')
  const remove = page.getByRole('button', { name: /^Remove / })
  while (await remove.count()) await remove.first().click()
  await expect(page.getByRole('heading', { name: 'No wallet methods yet' })).toBeVisible()
  await page.getByRole('button', { name: 'Add payment method', exact: true }).first().click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.locator('input')).toHaveCount(0)
  await expect(dialog.getByRole('combobox')).toHaveCount(4)
  await dialog.getByRole('button', { name: 'Add to My Wallet' }).click()
  await expect(page.getByRole('switch')).toHaveCount(1)
  await page.reload()
  await expect(page.getByRole('switch')).toHaveAttribute('aria-checked', 'true')
  await page.getByRole('link', { name: 'PayLess home' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#main-content')).toBeFocused()
  await page.getByRole('link', { name: 'Skip to content' }).focus()
  await expect(page.getByRole('link', { name: 'Skip to content' })).toBeVisible()
  await page.keyboard.press('Enter')
  await expect(page.locator('#main-content')).toBeFocused()
})

test('errors are associated, unknown service details are hidden and deep links reload', async ({ page }) => {
  await page.goto('/')
  await page.route('**/api/optimize/query', route => route.fulfill({ status: 500, json: { detail: 'SQLException private stack trace' } }))
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
  await expect(page.getByRole('alert')).toContainText('Service temporarily unavailable')
  await expect(page.getByLabel('What are you paying for?')).toHaveAttribute('aria-describedby', 'query-hint search-error')
  await expect(page.locator('body')).not.toContainText('SQLException')
  await page.screenshot({ path: `test-results/payless-error-${test.info().project.name}.png`, fullPage: true })
  await page.goto('/travel')
  await page.reload()
  await expect(page.getByLabel('Departure', { exact: true })).toBeVisible()
  await page.goto('/not-a-page')
  await expect(page.getByRole('heading', { name: 'This route doesn’t exist.' })).toBeVisible()
  await page.getByRole('link', { name: 'Back to Home' }).click()
  await expect(page.getByLabel('What are you paying for?')).toBeVisible()
})
