import { test, expect, type Page } from '@playwright/test'

test.beforeEach(async ({ request }) => {
  await request.post('http://127.0.0.1:18000/__control', { data: { mode: 'normal' } })
})
async function submit(page: Page) {
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
}
async function checkPopup(page: Page, name: RegExp, destination: string) {
  const link = page.getByRole('article', { name: 'Best Payment Route', exact: true }).getByRole('link', { name })
  await expect(link).toHaveAttribute('href', destination)
  await expect(link).toHaveAttribute('target', '_blank')
  await expect(link).toHaveAttribute('rel', 'noopener noreferrer')
  await page.context().route(destination, route => route.fulfill({ contentType: 'text/html', body: '<title>Provider</title>' }))
  const opened = page.waitForEvent('popup')
  await link.click()
  const popup = await opened
  await popup.waitForLoadState()
  expect(popup.url()).toBe(destination)
  expect(await popup.evaluate(() => window.opener === null)).toBe(true)
  await popup.close()
}

test('Swiggy ₹500 uses Spring, displays exact costs, and opens safe voucher and terms links', async ({ page }) => {
  const errors: string[] = []
  const network: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  page.on('request', r => network.push(r.url()))
  await page.goto('/')
  await page.getByLabel('What are you paying for?').fill("I'm ordering on Swiggy for ₹500")
  const responsePromise = page.waitForResponse('**/api/optimize/query')
  await submit(page)
  const response = await responsePromise
  expect(response.status()).toBe(200)
  expect(response.request().postDataJSON().wallet).toContainEqual({ issuer: 'HDFC', productName: 'HDFC Millennia Credit Card', instrumentType: 'CREDIT_CARD', network: 'VISA' })
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹487.50')
  await expect(page.getByTestId('best-effective')).toHaveText('₹487.50')
  const best = page.getByRole('article', { name: 'Best Payment Route', exact: true })
  await expect(best).toContainText('₹12.50')
  await expect(best).toContainText('Voucher covers purchase')
  await expect(best.locator('.live-steps > li')).toHaveCount(4)
  await expect(page.getByText('Fixture offers', { exact: true })).toBeVisible()
  await checkPopup(page, /Buy Voucher/, 'https://www.gyftr.com/swiggy-money')
  await checkPopup(page, /View Offer Terms/, 'https://www.gyftr.com/swiggy-money')
  expect(network.some(url => /:8000|:18000|\/scrape/.test(url))).toBe(false)
  await page.screenshot({ path: 'test-results/swiggy-' + test.info().project.name + '.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('Delhi to Mumbai combines demo fares, acquired offers, and wallet through Spring', async ({ page }) => {
  await page.goto('/travel')
  await page.getByLabel('Passengers', { exact: true }).selectOption('2')
  const responsePromise = page.waitForResponse('**/api/travel/optimize')
  await submit(page)
  const response = await responsePromise
  expect(response.status()).toBe(200)
  const body = await response.json()
  expect(body.fares).toHaveLength(2)
  expect(body.optimization.sources.map((s: { provider: string }) => s.provider)).toEqual(['YATRA', 'EASEMYTRIP'])
  await expect(page.getByRole('region', { name: 'Fare options' })).toContainText('₹11,300')
  await expect(page.getByRole('region', { name: 'Fare options' })).toContainText('₹10,918')
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹10,918')
  await expect(page.getByRole('article', { name: 'Best Payment Route', exact: true })).toContainText('EaseMyTrip')
  await page.getByRole('button', { name: 'Compare routes' }).click()
  await expect(page.getByRole('table')).toContainText('Yatra')
  await page.getByText('Provider status & eligibility details', { exact: true }).click()
  await expect(page.locator('.live-diagnostics')).toContainText('usage rule unconfirmed')
  await checkPopup(page, /Open EASEMYTRIP/, 'https://www.easemytrip.com/')
  await page.screenshot({ path: 'test-results/travel-' + test.info().project.name + '.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('validation and empty fare results remain editable', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('What are you paying for?').fill('Swiggy')
  await submit(page)
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByRole('link', { name: 'Travel', exact: true }).click()
  await page.getByLabel('To', { exact: true }).selectOption('Delhi')
  await submit(page)
  await expect(page.getByRole('alert')).toContainText('Choose different cities')
  await page.getByLabel('To', { exact: true }).selectOption('Chennai')
  await submit(page)
  await expect(page.getByRole('heading', { name: 'No routes found.' })).toBeVisible()
  await expect(page.getByText(/No fares available/)).toBeVisible()
  await page.getByRole('link', { name: 'Edit search' }).click()
  await expect(page.getByLabel('To', { exact: true })).toHaveValue('Chennai')
})

test('partial and total acquisition failures preserve direct routes and allow recovery', async ({ page, request }) => {
  await request.post('http://127.0.0.1:18000/__control', { data: { mode: 'partial' } })
  await page.goto('/travel')
  await submit(page)
  await expect(page.getByText('Some providers returned incomplete offers.')).toBeVisible()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹5,459')
  await request.post('http://127.0.0.1:18000/__control', { data: { mode: 'unavailable' } })
  await page.getByRole('button', { name: 'Refresh offers' }).click()
  await expect(page.getByText('Live offers are unavailable.')).toBeVisible()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹5,459')
  await request.post('http://127.0.0.1:18000/__control', { data: { mode: 'normal' } })
  await page.getByRole('button', { name: 'Refresh offers' }).click()
  await expect(page.getByText('Live offers are unavailable.')).toHaveCount(0)
  await expect(page.getByTestId('best-pay-now')).toBeVisible()
})

test('API failure, real loading state, cancellation, retry, and wallet persistence', async ({ page }) => {
  await page.goto('/')
  await page.route('**/api/optimize/query', route => route.fulfill({ status: 503, json: { detail: 'Service temporarily unavailable.' } }))
  await submit(page)
  await expect(page.getByRole('alert')).toContainText('Service temporarily unavailable.')
  await page.unroute('**/api/optimize/query')
  let release!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/optimize/query', async route => { await gate; await route.continue().catch(() => {}) })
  await submit(page)
  await expect(page.getByRole('status')).toContainText('Checking offers')
  await expect(page.getByRole('button', { name: 'Finding payment routes…' })).toBeDisabled()
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  release()
  await page.unroute('**/api/optimize/query')
  await expect(page.getByRole('status')).toHaveCount(0)
  await page.getByLabel('ICICI Credit Card', { exact: true }).uncheck()
  await page.reload()
  await expect(page.getByLabel('ICICI Credit Card', { exact: true })).not.toBeChecked()
  await submit(page)
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹487.50')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Let’s find your next route.' })).toBeVisible()
})
