import { test, expect, type Locator, type Page } from '@playwright/test'

async function checkExternalAction(page: Page, link: Locator, destination: string) {
  await expect(link).toHaveAttribute('href', destination)
  await expect(link).toHaveAttribute('target', '_blank')
  await expect(link).toHaveAttribute('rel', 'noopener noreferrer')
  // Exercise the actual new-tab action without sending test traffic to providers.
  await page.context().route(destination, route => route.fulfill({ contentType: 'text/html', body: '<title>Provider destination</title>' }))
  const opened = page.waitForEvent('popup')
  await link.click()
  const popup = await opened
  await popup.waitForLoadState()
  expect(popup.url()).toBe(destination)
  expect(await popup.evaluate(() => window.opener === null)).toBe(true)
  await popup.close()
}

test('judge journey: wallet → flight → explanation → comparison → checkout → Swiggy', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /lowest price/ })).toBeVisible()
  await page.screenshot({ path: `test-results/home-${test.info().project.name}.png`, fullPage: true })
  await page.getByRole('link', { name: /My Wallet/ }).click()
  await expect(page.getByRole('heading', { name: 'My Wallet.' })).toBeVisible()
  await page.getByRole('button', { name: 'Add Payment Product' }).click()
  await page.getByLabel('Bank / Issuer').selectOption('ICICI Bank')
  await page.getByLabel('Product', { exact: true }).selectOption('icici-coral')
  await page.getByRole('button', { name: 'Add to My Wallet' }).click()
  await expect(page.getByRole('switch', { name: 'Select ICICI Coral Credit Card' })).toBeChecked()
  await page.getByRole('button', { name: 'Remove ICICI Coral Credit Card' }).click()
  await expect(page.getByRole('switch', { name: 'Select ICICI Coral Credit Card' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Back to search' }).click()
  await page.getByRole('button', { name: /Book a Flight/ }).click()
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
  await expect(page.getByRole('heading', { name: /Finding your cheapest/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Best Route Found.' })).toBeVisible()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹4,988')
  await expect(page.getByTestId('best-effective')).toHaveText('₹4,908')
  await page.screenshot({ path: `test-results/results-${test.info().project.name}.png`, fullPage: true })
  const breakdown = page.locator('details').filter({ has: page.locator('summary', { hasText: 'Cost breakdown' }) })
  await expect(breakdown.locator('.effective-line')).toContainText('₹4,908')
  await breakdown.locator('summary').click()
  await expect(breakdown.locator('.effective-line')).not.toBeVisible()
  await breakdown.locator('summary').click()
  await expect(page.getByText('ICICI Credit Card selected', { exact: true })).toBeVisible()
  await page.locator('summary').filter({ hasText: 'Source & verification' }).click()
  await expect(page.getByText('Not performed — sample information only')).toBeVisible()
  await page.locator('summary').filter({ hasText: 'Offer Conditions' }).click()
  await expect(page.getByText('ICICI12', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Compare the two' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('table')).toContainText('EaseMyTrip')
  await expect(page.getByRole('table')).toContainText('₹5,459')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByLabel('Sort routes').selectOption('rewards')
  await expect(page.locator('.route-row').first()).toContainText('ixigo')
  await page.getByLabel('Sort routes').selectOption('pay-now')
  await expect(page.locator('.route-row').first()).toContainText('Cleartrip')
  await page.getByRole('button', { name: 'View Route', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your checkout guide' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'How to complete this route' })).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('does not create a pre-filled booking')
  await checkExternalAction(page, page.getByRole('dialog').getByRole('link', { name: /Open Yatra/ }), 'https://www.yatra.com/')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('link', { name: 'Home', exact: true }).first().click()
  await page.getByRole('button', { name: /Pay for Swiggy/ }).click()
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹487.50')
  await expect(page.getByTestId('best-effective')).toHaveText('₹487.50')
  await expect(page.getByText('₹12.50 total Savings', { exact: true })).toBeVisible()
  await page.screenshot({ path: `test-results/swiggy-${test.info().project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'View Route', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Redeem on Swiggy' })).toBeVisible()
  await checkExternalAction(page, page.getByRole('dialog').getByRole('link', { name: /Buy Voucher/ }), 'https://www.gyftr.com/')
  await checkExternalAction(page, page.getByRole('dialog').getByRole('link', { name: /Open Swiggy/ }), 'https://www.swiggy.com/')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.reload()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹487.50')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('fallbacks, wallet changes, recent searches, and reset work', async ({ page }) => {
  await page.goto('/results')
  await expect(page.getByRole('heading', { name: 'Let’s find your first route.' })).toBeVisible()
  await page.getByRole('link', { name: 'Start a search' }).click()
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹4,988')
  await page.locator('summary').filter({ hasText: 'Demo controls' }).click()
  await page.getByLabel('Demo result state').selectOption('no-offer')
  await expect(page.getByText(/No special offer matches/)).toBeVisible()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹5,459')
  await page.getByLabel('Demo result state').selectOption('stale')
  await expect(page.getByText('Stale offers are excluded', { exact: false })).toBeVisible()
  await page.getByLabel('Demo result state').selectOption('ambiguous')
  await expect(page.getByText(/We found conflicting conditions in the source/)).toBeVisible()
  await page.getByLabel('Demo result state').selectOption('normal')
  await page.getByRole('button', { name: 'Try with an empty wallet' }).click()
  await expect(page.getByText(/We can still compare merchant prices/)).toBeVisible()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹5,459')
  await page.getByRole('link', { name: 'Add payment products', exact: true }).click()
  await page.getByRole('button', { name: 'Restore demo wallet' }).click()
  await page.getByRole('link', { name: 'See updated routes' }).click()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹4,988')
  await page.getByRole('link', { name: 'Recent Searches' }).click()
  await expect(page.locator('.recent-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Run again' }).click()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹4,988')
  await page.getByRole('button', { name: 'Open demo profile' }).click()
  await page.getByRole('button', { name: 'Reset all demo data' }).click()
  await expect(page.getByRole('heading', { name: /lowest price/ })).toBeVisible()
  await page.getByRole('link', { name: 'Recent Searches' }).click()
  await expect(page.getByRole('heading', { name: 'Your next great route starts here.' })).toBeVisible()
  await page.goto('/not-a-route')
  await expect(page.getByRole('heading', { name: 'This route doesn’t exist.' })).toBeVisible()
})

test('search validation, keyboard dismissal, and compare limit', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('To', { exact: true }).selectOption('Delhi')
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
  await expect(page.getByRole('alert')).toHaveText('Choose different departure and arrival cities.')
  await page.getByRole('button', { name: /Book a Flight/ }).click()
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
  await expect(page.getByTestId('best-pay-now')).toBeVisible()
  await page.locator('.best-route-card').getByRole('checkbox').check()
  await page.locator('.route-row').nth(0).getByRole('checkbox').check()
  await page.locator('.route-row').nth(1).getByRole('checkbox').check()
  await page.locator('.route-row').nth(2).getByRole('checkbox').click()
  await expect(page.getByRole('status')).toContainText('Compare up to 3 routes')
  await expect(page.locator('.compare-bar')).toContainText('3 of 3 routes selected')
  await page.getByRole('button', { name: 'Compare Routes', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('free-form Swiggy journey shows interpretation, exact savings, provenance and safe actions', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('What are you buying?').fill("I'm ordering food on swigy and it costs 500 rs")
  await page.getByRole('button', { name: 'Review purchase' }).click()
  const interpretation = page.getByRole('region', { name: 'Purchase interpretation' })
  await expect(interpretation).toContainText('Swiggy')
  await expect(interpretation).toContainText('₹500')
  await expect(interpretation).toContainText('Food Delivery')
  await page.screenshot({ path: `test-results/query-${test.info().project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
  await expect(page.getByRole('heading', { name: /Finding your cheapest/ })).toBeVisible()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹487.50')
  await expect(page.getByTestId('best-effective')).toHaveText('₹487.50')
  await expect(page.locator('.voucher-calculation')).toContainText('₹500 × 2.5% = ₹12.50')
  await expect(page.locator('.winner-provenance')).toContainText('Last verified: 18 Sept 2026 (demo)')
  await expect(page.locator('.eligibility-list')).toContainText('UPI selected')
  await expect(page.locator('.route-row')).toHaveCount(2)
  await expect(page.locator('.route-row').filter({ hasText: 'HDFC Millennia' })).toContainText('₹495')
  await expect(page.locator('.route-row').filter({ hasText: 'UPI' })).toContainText('₹500')
  await checkExternalAction(page, page.locator('.best-route-card').getByRole('link', { name: /Buy Voucher/ }), 'https://www.gyftr.com/')
  await page.getByRole('button', { name: 'View Route', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.locator('.guide-steps > li')).toHaveCount(2)
  await expect(dialog.locator('.guide-steps > li').first()).toContainText('Buy ₹500 Swiggy Money voucher for ₹487.50 from GyFTR')
  await expect(dialog.locator('.guide-steps > li').nth(1)).toContainText('Redeem on Swiggy')
  await dialog.locator('summary').filter({ hasText: 'Source & verification' }).click()
  await expect(dialog.getByRole('link', { name: /Open source page/ })).toHaveAttribute('href', 'https://www.gyftr.com/luminous/vouchers/brand/swiggy-money-voucher-gift-vouchers')
  await checkExternalAction(page, dialog.getByRole('link', { name: /Buy Voucher/ }), 'https://www.gyftr.com/')
  await checkExternalAction(page, dialog.getByRole('link', { name: /Open Swiggy/ }), 'https://www.swiggy.com/')
  await dialog.locator('.guide-heading').scrollIntoViewIfNeeded()
  await page.screenshot({ path: `test-results/route-steps-${test.info().project.name}.png`, fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('link', { name: 'Edit search' }).click()
  await expect(page.getByLabel('What are you buying?')).toHaveValue('500 rupees on Swiggy')
  expect(errors).toEqual([])
})

test('missing fields, corrections, unknown merchants and examples preserve purchase intent', async ({ page }) => {
  await page.goto('/')
  const input = page.getByLabel('What are you buying?')
  await input.fill('Can I save on Swiggy?')
  await page.getByRole('button', { name: 'Review purchase' }).click()
  await expect(page.getByText('How much is your Swiggy order?')).toBeVisible()
  await expect(page.getByLabel('Purchase Amount', { exact: true })).toHaveValue('')
  await expect(page.getByRole('button', { name: 'Find Best Payment Route' })).toHaveCount(0)
  await page.getByLabel('Purchase Amount', { exact: true }).fill('500.50')
  await page.getByRole('button', { name: 'Confirm purchase' }).click()
  await expect(page.getByRole('region', { name: 'Purchase interpretation' })).toContainText('₹500.50')
  await input.fill('How can I save on ₹500?')
  await expect(page.getByRole('button', { name: 'Find Best Payment Route' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Review purchase' }).click()
  await expect(page.getByText('Where are you making this ₹500 purchase?')).toBeVisible()
  await expect(page.getByLabel('Merchant', { exact: true })).toHaveValue('')
  await page.getByLabel('Merchant', { exact: true }).selectOption('ZOMATO')
  await page.getByRole('button', { name: 'Confirm purchase' }).click()
  await page.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByLabel('Merchant', { exact: true }).selectOption('MYNTRA')
  await page.getByLabel('Purchase Amount', { exact: true }).fill('1000')
  await page.getByRole('button', { name: 'Confirm purchase' }).click()
  await expect(page.getByRole('region', { name: 'Purchase interpretation' })).toContainText('Fashion')
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹1,000')
  await expect(page.locator('.best-route-card')).toContainText('Myntra')
  await expect(page.getByText(/No special offer matches/)).toBeVisible()
  await expect(page.locator('.best-route-card').getByRole('link', { name: /Open Myntra/ })).toHaveAttribute('href', 'https://www.myntra.com/')
  await expect(page.locator('.best-route-card')).not.toContainText('Swiggy')
  await page.getByRole('link', { name: 'Edit search' }).click()
  await input.fill('₹500 on randommerchant')
  await page.getByRole('button', { name: 'Review purchase' }).click()
  await expect(page.getByLabel('Merchant', { exact: true })).toHaveValue('')
  await page.getByRole('button', { name: '₹1,000 on Myntra', exact: true }).click()
  await expect(input).toHaveValue('₹1,000 on Myntra')
  await expect(page.getByRole('region', { name: 'Purchase interpretation' })).toContainText('Fashion')
  await page.getByRole('button', { name: 'Delhi → Mumbai flight', exact: true }).click()
  await expect(page.getByRole('tab', { name: 'Travel', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByLabel('From', { exact: true })).toHaveValue('Delhi')
  await expect(page.getByLabel('To', { exact: true })).toHaveValue('Mumbai')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Home recent shortcuts restore the selected purchase and fit a narrow screen', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '₹500 on Swiggy', exact: true }).click()
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹487.50')
  await page.getByRole('link', { name: 'Edit search' }).click()
  await page.getByRole('button', { name: '₹1,000 on Myntra', exact: true }).click()
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹1,000')
  await page.getByRole('link', { name: 'Edit search' }).click()
  await page.locator('.recent-mini').filter({ hasText: 'Swiggy' }).click()
  await expect(page.getByLabel('What are you buying?')).toHaveValue('500 rupees on Swiggy')
  await page.setViewportSize({ width: 320, height: 800 })
  await page.getByRole('region', { name: 'Purchase interpretation' }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Find Best Payment Route' }).click()
  await expect(page.getByTestId('best-pay-now')).toHaveText('₹487.50')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'View Route', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('link', { name: /Buy Voucher/ })).toBeVisible()
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
})
