from enum import StrEnum


class ProviderId(StrEnum):
    GYFTR = "GYFTR"
    YATRA = "YATRA"
    EASEMYTRIP = "EASEMYTRIP"


class OfferType(StrEnum):
    VOUCHER_DISCOUNT = "VOUCHER_DISCOUNT"
    INSTANT_DISCOUNT = "INSTANT_DISCOUNT"
    CASHBACK = "CASHBACK"
    COUPON = "COUPON"
    BANK_OFFER = "BANK_OFFER"
    PAYMENT_METHOD_DISCOUNT = "PAYMENT_METHOD_DISCOUNT"
    UNKNOWN = "UNKNOWN"


class TransactionMode(StrEnum):
    VOUCHER = "VOUCHER"
    CREDIT_CARD = "CREDIT_CARD"
    DEBIT_CARD = "DEBIT_CARD"
    CARD = "CARD"
    UPI = "UPI"
    EMI = "EMI"
    NET_BANKING = "NET_BANKING"
    WALLET = "WALLET"
    UNKNOWN = "UNKNOWN"


class DiscountType(StrEnum):
    PERCENTAGE = "PERCENTAGE"
    FLAT = "FLAT"
    CASHBACK = "CASHBACK"
    VARIABLE = "VARIABLE"
    UNKNOWN = "UNKNOWN"


class VerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    AMBIGUOUS = "AMBIGUOUS"
    INCOMPLETE = "INCOMPLETE"


class StackingPolicy(StrEnum):
    ALLOWED = "ALLOWED"
    NOT_ALLOWED = "NOT_ALLOWED"
    UNKNOWN = "UNKNOWN"


class Availability(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    UNKNOWN = "UNKNOWN"


class FetchMethod(StrEnum):
    HTTP = "HTTP"
    BROWSER = "BROWSER"
    FIXTURE = "FIXTURE"


class ScrapeStatus(StrEnum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class ErrorCode(StrEnum):
    DNS_ERROR = "DNS_ERROR"
    CONNECT_TIMEOUT = "CONNECT_TIMEOUT"
    READ_TIMEOUT = "READ_TIMEOUT"
    TLS_ERROR = "TLS_ERROR"
    HTTP_403 = "HTTP_403"
    HTTP_404 = "HTTP_404"
    HTTP_429 = "HTTP_429"
    HTTP_5XX = "HTTP_5XX"
    REDIRECT_LOOP = "REDIRECT_LOOP"
    BLOCK_PAGE = "BLOCK_PAGE"
    EMPTY_RESPONSE = "EMPTY_RESPONSE"
    UNSUPPORTED_CONTENT_TYPE = "UNSUPPORTED_CONTENT_TYPE"
    BROWSER_NAVIGATION_FAILED = "BROWSER_NAVIGATION_FAILED"
    BROWSER_BLOCK_PAGE = "BROWSER_BLOCK_PAGE"
    PARSE_FAILED = "PARSE_FAILED"
    JS_RENDER_REQUIRED = "JS_RENDER_REQUIRED"
    PROVIDER_DISABLED = "PROVIDER_DISABLED"
    PROVIDER_NOT_SUPPORTED = "PROVIDER_NOT_SUPPORTED"
    MERCHANT_NOT_SUPPORTED = "MERCHANT_NOT_SUPPORTED"
    ROBOTS_DISALLOWED = "ROBOTS_DISALLOWED"
    FETCH_TIMEOUT = "FETCH_TIMEOUT"
    FETCH_FORBIDDEN = "FETCH_FORBIDDEN"
    FETCH_RATE_LIMITED = "FETCH_RATE_LIMITED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    CONTENT_TYPE_INVALID = "CONTENT_TYPE_INVALID"
    RESPONSE_TOO_LARGE = "RESPONSE_TOO_LARGE"
    URL_NOT_ALLOWED = "URL_NOT_ALLOWED"
    PARSER_FAILED = "PARSER_FAILED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    NO_OFFERS_FOUND = "NO_OFFERS_FOUND"
    BROWSER_FAILED = "BROWSER_FAILED"
    BAD_REQUEST = "BAD_REQUEST"
    INTERNAL_ERROR = "INTERNAL_ERROR"
