import { ChevronDown, CreditCard } from 'lucide-react'
import { InfoTip } from '../../../shared/components/UI'
import { money } from '../model/presentation'
import type { PaymentRoute } from '../model/types'

export function CostBreakdown({ route, open = false }: { route: PaymentRoute; open?: boolean }) {
  return <details className="explanation panel" open={open || undefined}><summary><span><span className="section-icon"><CreditCard size={17} /></span>Cost breakdown</span><ChevronDown size={17} /></summary><div className="explanation-body"><dl className="cost-lines"><div><dt>{route.isVoucher ? 'Voucher face value' : 'Fare / Booking Amount'}</dt><dd>{money(route.base)}</dd></div><div><dt>Convenience Fee</dt><dd>{money(route.fees)}</dd></div><div className="savings-text"><dt>Instant Discount</dt><dd>−{money(route.discount)}</dd></div><div className="total-line"><dt>Pay Now</dt><dd>{money(route.payNow)}</dd></div><div><dt>Estimated Rewards <InfoTip>Cashback and rewards arrive later and are not deducted from the checkout payment. Values are illustrative.</InfoTip></dt><dd className="savings-text">−{money(route.rewards)}</dd></div><div className="effective-line"><dt>Effective Cost</dt><dd>{money(route.effective)}</dd></div></dl><p className="voucher-calculation">{route.isVoucher ? `${money(route.base)} × 2.5% = ${money(route.discount)} discount (maximum ₹25). ` : ''}{money(route.base)} + {money(route.fees)} fees − {money(route.discount)} discount = {money(route.payNow)} Pay Now. {money(route.payNow)} − {money(route.rewards)} rewards = {money(route.effective)} Effective Cost.</p><p className="fine-print">{route.offer?.assumption ?? 'No promotional discount or deferred rewards assumed. Pay Now and Effective Cost are equal.'}</p>{route.discount > 0 && <p className="fine-print">Eligible Amount: {money(route.base)}. Discount excludes fees{route.isVoucher ? ', rounded to the nearest paise.' : ' and is rounded down to a whole rupee under the demo terms.'}</p>}</div></details>
}

