import { useOptimizationController } from '../controller/useOptimizationController'
import { excludedReason } from '../model/selectors'
import { PaymentRouteCard } from './PaymentRouteCard'
import { Link } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Check, ChevronDown, CircleAlert, GitCompareArrows, Info, Plane, RotateCcw, Settings2, ShieldCheck, ShoppingBag, SlidersHorizontal, Sparkles, Trophy, Wallet, X } from 'lucide-react'
import { dateLabel, money, purchaseLabel } from '../model/presentation'
import { Badge, OfferBadge } from '../../../shared/components/UI'
import { RouteFlow } from './RouteFlow'
import { CostBreakdown, EligibilityChecklist, OfferConditions, RewardNote, SourceVerification } from './RouteExplanation'
import { RouteDetails } from './RouteDetails'
import { RouteComparison } from './RouteComparison'
import { ExternalAction } from './ExternalAction'
import type { Scenario, Sort } from '../model/types'

export function ResultsPage() {
  const { purchase, searched, scenario, setScenario, sort, setSort, selected, setSelected, compare, setCompare, detail, setDetail, showAll, setShowAll, toggleCompare, clearWallet, comparisonRoutes, ranked, best, nextAction, lowestPay, alternatives, excluded, activeWallet, cheapestListed } = useOptimizationController()
  if (!searched) return <main className="page"><div className="empty-state panel"><GitCompareArrows size={40} /><h1>Let’s find your first route.</h1><p>Start with a purchase to compare your payment options.</p><Link className="button button-primary" to="/">Start a search<ArrowRight size={17} /></Link></div></main>
  return <main className="page results-page"><div className="results-breadcrumb"><Link to="/">Home</Link><span>/</span><span>Payment Routes</span><Badge>Demo Data</Badge></div><div className="search-summary"><div className="search-summary-icon">{purchase.mode === 'travel' ? <Plane size={22} /> : <ShoppingBag size={22} />}</div><div><strong>{purchaseLabel(purchase)}</strong><span>{purchase.mode === 'travel' ? `${dateLabel(purchase.departure)} · ${purchase.passengers} ${purchase.passengers === 1 ? 'adult' : 'adults'} · Economy · One way` : `${purchase.category} · Order amount ${money(purchase.amount)}`}</span></div><Link className="button button-secondary button-small" to="/">Edit search<SlidersHorizontal size={14} /></Link></div>
    <div className="page-title-row results-title"><div><span className="result-eyebrow"><span className="success-ring"><Check size={12} /></span>{ranked.length} ROUTES COMPARED · PERSONALIZED TO YOUR WALLET</span><h1>Best Route Found<span className="title-dot">.</span></h1><p>The complete picture, from purchase to payment.</p></div><details className="demo-controls"><summary><Settings2 size={15} />Demo controls<ChevronDown size={14} /></summary><div><label>Explore a result state<select aria-label="Demo result state" value={scenario} onChange={event => { setScenario(event.target.value as Scenario); setSelected([]); setShowAll(false) }}><option value="normal">Standard demo</option><option value="no-offer">No eligible offer</option><option value="stale">Stale offer sources</option><option value="ambiguous">Conflicting source terms</option></select></label><button className="text-button" onClick={event => { event.currentTarget.closest("details")?.removeAttribute("open"); clearWallet() }}><Wallet size={14} />Try with an empty wallet</button><Link to="/wallet" className="text-button"><RotateCcw size={14} />Manage or restore wallet</Link><p>These controls simulate the prototype’s fallback states.</p></div></details></div>
    {!activeWallet && <div className="notice notice-primary result-notice"><Wallet size={21} /><div><strong>Your wallet has more possibilities.</strong><p>We can still compare merchant prices, but adding your payment products can unlock personalized savings.</p></div><Link className="button button-secondary button-small" to="/wallet">Add payment products<ArrowRight size={14} /></Link></div>}
    {activeWallet > 0 && !best.offer && <div className="notice notice-amber result-notice"><Info size={21} /><div><strong>No special offer matches this purchase and your current wallet{scenario !== 'normal' ? ' in this demo state' : ''}.</strong><p>We’ve selected the best available direct payment route. Only offers for this merchant in the demo dataset are considered.</p></div><Link className="text-button" to="/wallet">My Wallet<ArrowRight size={15} /></Link></div>}
    {scenario === 'stale' && <div className="notice notice-amber"><CircleAlert size={20} /><p><strong>Offer information may be outdated.</strong> Stale offers are excluded from the top recommendation. View their sources below.</p></div>}
    {scenario === 'ambiguous' && <div className="notice notice-amber"><CircleAlert size={20} /><p>We found conflicting conditions in the source. These offers have been excluded from the top recommendation.</p></div>}
    <section className="best-route-card" aria-label="Best Payment Route"><div className="best-route-main"><div className="best-route-heading"><Badge tone="primary"><Trophy size={13} />Best Overall</Badge><span>LOWEST EFFECTIVE COST</span><OfferBadge status={best.status} /></div><h2>{best.offer ? <>{best.isVoucher ? 'A small detour. A better deal.' : 'The right price meets the right card.'}</> : 'Your best available direct payment route.'}</h2><p className="best-route-description">{best.isVoucher ? 'Buy a discounted Swiggy Money voucher, then redeem it on your order.' : best.offer ? `Choose ${best.merchant} and pay with your ${best.paymentName}.` : `Buy from ${best.merchant} and pay ${money(best.payNow)} at checkout.`}</p><RouteFlow route={best} purchase={purchase} /><div className="best-route-bottom"><span className="savings-line"><Sparkles size={17} /><strong>{money(best.savings)} total Savings</strong><span>vs. this merchant without an offer</span></span><label className="compare-checkbox"><input type="checkbox" checked={selected.includes(best.id)} onChange={() => toggleCompare(best.id)} />Compare</label></div></div><div className="best-route-totals"><div className="main-metric"><span>PAY NOW</span><strong data-testid="best-pay-now">{money(best.payNow)}</strong><p>What leaves your account at checkout.</p></div><div className="effective-metric"><div><span>EFFECTIVE COST</span><Badge tone="green">After rewards</Badge></div><strong data-testid="best-effective">{money(best.effective)}</strong><p>Pay Now minus estimated cashback/reward value.</p></div><ExternalAction url={nextAction?.actionUrl} label={nextAction?.actionLabel} primary /><small className="action-destination">{best.isVoucher ? 'Opens GyFTR catalogue · demo price' : 'Opens provider homepage'}</small><button className="button button-secondary" onClick={() => setDetail(best)}>View Route<ArrowRight size={17} /></button></div></section>
    <div className="winner-provenance"><ShieldCheck size={15} /><span>Source: sample {best.isVoucher ? 'GyFTR / Swiggy voucher' : best.merchant} fixture</span><span>Last verified: {dateLabel(best.lastVerifiedAt)} (demo)</span><OfferBadge status={best.status} /></div><RewardNote route={best} />
    {purchase.mode === 'travel' && best.offer && cheapestListed.merchant !== best.merchant && <div className="price-insight"><span className="insight-icon"><Info size={20} /></span><p><strong>The lowest listed fare isn’t the lowest final cost.</strong> {cheapestListed.merchant} lists {money(cheapestListed.base)}, but costs {money(cheapestListed.payNow)} with fees and no offer. This {best.merchant} route costs {money(best.payNow)} at checkout.</p><button className="text-button" onClick={() => { setSelected([best.id, cheapestListed.id]); setCompare(true) }}>Compare the two<ArrowRight size={14} /></button></div>}
    {lowestPay.id !== best.id && <div className="pay-now-insight"><span><strong>Prefer paying less today?</strong> {lowestPay.merchant} has the lowest Pay Now at <strong>{money(lowestPay.payNow)}</strong>, with an Effective Cost of {money(lowestPay.effective)}.</span><button className="text-button" onClick={() => setDetail(lowestPay)}>View route<ArrowRight size={14} /></button></div>}
    <div className="explanation-grid"><div className="stack"><CostBreakdown key={`cost-${best.id}`} route={best} open /><OfferConditions route={best} /></div><div className="stack"><EligibilityChecklist key={`eligibility-${best.id}`} route={best} open /><SourceVerification route={best} /></div></div>
    <section className="alternatives-section"><div className="section-heading"><div><span className="eyebrow">EVERY OPTION, IN THE OPEN</span><h2>Other ways to pay <span className="heading-count">{alternatives.length}</span></h2><p>Select up to 3 routes to compare the complete cost.</p></div><label className="sort-control"><span><SlidersHorizontal size={14} />Sort by</span><select aria-label="Sort routes" value={sort} onChange={event => setSort(event.target.value as Sort)}><option value="overall">Best Overall</option><option value="pay-now">Lowest Pay Now</option><option value="rewards">Highest Rewards</option></select></label></div><div className="route-table panel"><div className="route-table-header"><span>MERCHANT & PAYMENT</span><span>PAY NOW</span><span>EFFECTIVE COST</span><span>SAVINGS</span><span /></div>{(showAll ? alternatives : alternatives.slice(0, 5)).map((route, index) => <PaymentRouteCard route={route} index={index + 2} selected={selected.includes(route.id)} onSelect={() => toggleCompare(route.id)} onView={() => setDetail(route)} key={route.id} lowestPay={lowestPay.id === route.id} />)}{alternatives.length === 0 && <div className="empty-alternatives"><Info size={20} /><p>No additional eligible routes for this wallet. Add a payment product or try the standard demo.</p><Link to="/wallet" className="text-button">Add payment products<ArrowRight size={14} /></Link></div>}{alternatives.length > 5 && <button className="show-routes" onClick={() => setShowAll(!showAll)}>{showAll ? 'Show fewer routes' : `Show all ${alternatives.length} alternative routes`}<ChevronDown size={15} /></button>}</div></section>
    {excluded.length > 0 && <details className="excluded-routes panel" open={scenario !== 'normal' || undefined}><summary><span><ShieldCheck size={18} /><strong>{excluded.length} offers excluded from recommendations</strong><span className="muted">Because the details matter.</span></span><ChevronDown size={17} /></summary><div className="excluded-content">{excluded.map(route => <div className="excluded-row" key={route.id}><span className="excluded-icon"><CircleAlert size={18} /></span><div><h3>{route.merchant} <Badge tone="amber">{route.stale ? 'Stale source' : route.status === 'AMBIGUOUS' ? 'Ambiguous source' : 'Not eligible'}</Badge></h3><p>{route.stale ? 'Offer information may be outdated.' : route.status === 'AMBIGUOUS' ? 'Conflicting conditions: one sample source requires EMI. This route is not automatically recommended.' : excludedReason(route)}</p></div><button className="text-button" onClick={() => setDetail(route)}>{route.stale || route.status === 'AMBIGUOUS' ? 'View source' : 'View eligibility'}<ArrowRight size={14} /></button></div>)}</div></details>}
    <div className="result-disclaimer"><ShieldCheck size={16} /><p>All fares, fees, offers and rewards are Demo Data. Effective Cost is an estimate, not the checkout amount. Confirm current terms with the merchant before a real purchase.</p></div><Link to="/" className="back-link"><ArrowLeft size={15} />Try another purchase</Link>
    {selected.length > 0 && <div className="compare-bar"><span className="compare-bar-icon"><GitCompareArrows size={22} /></span><div><strong>{selected.length} of 3 routes selected</strong><span>{selected.length < 2 ? 'Choose one more route to compare.' : 'See every part of the price, side by side.'}</span></div><button className="text-button" onClick={() => setSelected([])}>Clear<X size={14} /></button><button className="button button-primary" disabled={selected.length < 2} onClick={() => setCompare(true)}>Compare Routes<ArrowRight size={16} /></button></div>}
    {detail && <RouteDetails route={detail} purchase={purchase} onClose={() => setDetail(null)} />}
    {compare && <RouteComparison routes={comparisonRoutes} onClose={() => setCompare(false)} />}
  </main>
}
