import { useWalletController, useAddProductController } from '../controller/useWalletController'
import { Link } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Check, CreditCard, Info, LockKeyhole, Plus, RotateCcw, ShieldCheck, Smartphone, Trash2, Wallet as WalletIcon } from 'lucide-react'
import { Badge, Modal } from '../../../shared/components/UI'
import type { WalletProduct } from '../../optimization/model/types'

export function Wallet() {
  const { wallet, searched, adding, setAdding, active, toggle, selectAll, remove, restore } = useWalletController()
  return <main className="page wallet-page"><Link to="/" className="back-link"><ArrowLeft size={15} />Back to search</Link><div className="page-title-row"><div><span className="eyebrow">PERSONALIZED TO WHAT YOU OWN</span><h1>My Wallet<span className="title-dot">.</span></h1><p>Select your payment products. We’ll find the offers that fit.</p></div><button className="button button-primary" onClick={() => setAdding(true)}><Plus size={18} />Add Payment Product</button></div><div className="wallet-layout"><div><div className="wallet-section-heading"><h2>Your payment products <Badge tone="primary">{active} selected</Badge></h2><div className="wallet-selection-actions"><button className="text-button" onClick={() => selectAll(true)}>Select all</button><span>·</span><button className="text-button muted" onClick={() => selectAll(false)}>Clear selection</button></div></div>{wallet.length === 0 ? <div className="empty-state panel"><WalletIcon size={35} /><h3>A fresh start for your wallet</h3><p>Add a payment product to check personalized offers.</p><button className="button button-primary" onClick={() => setAdding(true)}><Plus size={17} />Add Payment Product</button></div> : <div className="wallet-grid">{wallet.map(product => <PaymentInstrumentCard key={product.id} product={product} onToggle={() => toggle(product.id)} onRemove={() => remove(product)} />)}</div>}<div className="wallet-bottom-actions"><p><Info size={15} />Selection changes are saved automatically in this browser.</p><button className="text-button" onClick={restore}><RotateCcw size={14} />Restore demo wallet</button></div></div><aside className="wallet-aside"><div className="panel wallet-summary"><span className="summary-wallet-icon"><WalletIcon size={24} /></span><h2>A wallet of possibilities.</h2><p>Each product you select helps us check another path to a better price.</p><div className="wallet-count"><strong>{active}</strong><span>payment products<br />ready to compare</span></div><Link className="button button-primary" to={searched ? '/results' : '/'}>{searched ? 'See updated routes' : 'Find my Payment Route'}<ArrowRight size={17} /></Link>{active === 0 && <p className="fine-print">We can still compare merchant prices. Adding payment products can unlock personalized savings.</p>}</div><div className="wallet-privacy"><LockKeyhole size={21} /><h3>Product names. Nothing sensitive.</h3><p>We store only the issuer, product, type and network you select.</p><ul><li><Check size={14} />No card numbers or CVV</li><li><Check size={14} />No OTP, PIN or bank connection</li><li><Check size={14} />Stored locally for this demo</li></ul><span><ShieldCheck size={14} />Your credentials stay with you.</span></div></aside></div>{adding && <AddProduct onClose={() => setAdding(false)} />}</main>
}

function PaymentInstrumentCard({ product, onToggle, onRemove }: { product: WalletProduct; onToggle: () => void; onRemove: () => void }) {
  return <article className={`payment-product ${product.selected ? 'selected' : ''}`}><div className="payment-product-top"><span className="issuer-logo" style={{ background: `${product.color}13`, color: product.color }}>{product.issuer === 'UPI' ? <Smartphone size={21} /> : product.issuer.split(' ')[0]}</span><button role="switch" aria-checked={product.selected} aria-label={`Select ${product.name}`} className={`toggle ${product.selected ? 'on' : ''}`} onClick={onToggle}><span>{product.selected && <Check size={11} />}</span></button></div><span className="issuer-name">{product.issuer}</span><h3>{product.name.replace(`${product.issuer.split(' ')[0]} `, '')}</h3><div className="product-type"><CreditCard size={14} />{product.type}<span>·</span>{product.network}</div><div className="payment-product-bottom"><span>{product.selected ? <><span className="selected-dot" />Included in your search</> : 'Not included in your search'}</span><button className="remove-product" aria-label={`Remove ${product.name}`} onClick={onRemove}><Trash2 size={15} /></button></div></article>
}

function AddProduct({ onClose }: { onClose: () => void }) {
  const { issuers, issuer, setIssuer, products, product, setProductId, exists, submit } = useAddProductController(onClose)
  return <Modal title="Add a payment product" onClose={onClose}><p className="muted mb-6">Choose the product you own. No account connection or card details required.</p><form className="add-product-form" onSubmit={event => { event.preventDefault(); submit() }}><label>Bank / Issuer<select aria-label="Bank / Issuer" value={issuer} onChange={event => { setIssuer(event.target.value); setProductId('') }}>{issuers.map(bank => <option key={bank}>{bank}</option>)}</select></label><label>Product<select aria-label="Product" value={product.id} onChange={event => setProductId(event.target.value)}>{products.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="form-two-column"><label>Card Type<select aria-label="Card Type" key={product.type} defaultValue={product.type}><option>{product.type}</option></select></label><label>Network<select aria-label="Network" key={product.network} defaultValue={product.network}><option>{product.network}</option></select></label></div><p className="fine-print">Type and network match the selected demo product.</p><div className="notice notice-primary"><LockKeyhole size={18} /><p>Only payment-product metadata is saved on this device.</p></div><button type="submit" className="button button-primary"><Plus size={17} />{exists ? 'Select existing product' : 'Add to My Wallet'}</button></form></Modal>
}
